PREFIX premis: <http://www.loc.gov/premis/rdf/v3/>
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX haObj: <https://data.hetarchief.be/ns/object/> 
PREFIX haDes: <https://data.hetarchief.be/ns/descriptive/> 
PREFIX haLicId: <https://data.hetarchief.be/id/license/>
PREFIX rel: <http://id.loc.gov/vocabulary/preservation/relationshipSubType/> 
PREFIX ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> 
prefix prov: <http://www.w3.org/ns/prov#>
# EBUCore - the Dublin Core for media
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> # XML Schema Definition
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT
?id
?intellectual_entity_id
?premis_medium
?schema_height
?schema_identifier
?schema_material
?schema_material_extent
?schema_name
?schema_width
?created_at
?updated_at
?bibframe_production_method
?ebucore_has_captioning
?type
WHERE {
    ?intellectual_entity_id rel:isr ?rep.
    ?rep premis:storedAt ?id.
    ?id a haObj:PhysicalCarrier;
    schema:name ?schema_name;
    premis:medium/skos:prefLabel ?premis_medium.

    FILTER EXISTS {
      ?intellectual_entity_id schema:license ?schema_license
      VALUES ?schema_license { haLicId:VIAA-PUBLIEK-METADATA-LTD haLicId:VIAA-PUBLIEK-METADATA-ALL haLicId:MEEMOO-BEZOEKERTOOL-METADATA haLicId:MEEMOO-BEZOEKERTOOL-CONTENT haLicId:VIAA-INTRA_CP-METADATA-ALL haLicId:VIAA-INTRA_CP-CONTENT }
    }

    FILTER (langMatches(lang(?schema_name), "nl") && langMatches(lang(?premis_medium), "en"))

    OPTIONAL {
      ?id schema:identifier ?schema_identifier
    }

    OPTIONAL {
      ?rep bf:productionMethod/skos:prefLabel ?bibframe_production_method.
      FILTER (langMatches(lang(?bibframe_production_method), "nl"))
    }
  
    OPTIONAL {
      ?id schema:height ?height.
      ?height schema:value ?height_value;
              schema:unitText ?height_unit.
      BIND( CONCAT(?height_value, ' ', ?height_unit) as ?schema_height)
    }
    
  
    OPTIONAL {
      ?id schema:width ?width.
      ?width schema:value ?width_value;
              schema:unitText ?width_unit.
      BIND( CONCAT(?width_value, ' ', ?width_unit) as ?schema_width)
    }
    
    OPTIONAL {
      ?id schema:materialExtent ?schema_material_extent
    }
    OPTIONAL {
      ?id schema:material ?schema_material
    }

    BIND(EXISTS {
      ?id ebucore:hasCaptioning/rdf:type ebucore:OpenCaptions 
    } AS ?ebucore_has_captioning)

    OPTIONAL {
      ?id a ?type_res.
      VALUES ?type_res { haDes:ImageReel haDes:AudioReel}
      ?type_res rdfs:label ?type.
      FILTER (langMatches(lang(?type), "nl"))
    }

}