prefix schema: <https://schema.org/>

SELECT ?intellectual_entity_id ?type ?val ?newspaper
WHERE {
  ?intellectual_entity_id schema:isPartOf ?id.
  ?id schema:name ?val; 
  a ?type .

  VALUES ?type { schema:CreativeWorkSeries schema:Newspaper schema:CreativeWorkSeason  }
}