PREFIX schema: <https://schema.org/>

SELECT DISTINCT 
?id 
?schema_name
?created_at
?updated_at
WHERE {
  {
    ?id a schema:Thing; schema:name ?schema_name.
    FILTER langMatches(lang(?schema_name), "nl")
  }
  UNION {
    ?id a schema:Person; schema:name ?schema_name.
    FILTER langMatches(lang(?schema_name), "nl")
  }
}