PREFIX schema: <https://schema.org/>

SELECT DISTINCT 
?id 
?schema_name
?schema_birth_date
?schema_birth_place
?schema_death_date
?schema_death_place
?created_at
?updated_at
WHERE {
  {
    ?id a schema:Thing; schema:name ?schema_name.
    FILTER langMatches(lang(?schema_name), "nl")
  }
  UNION {
    ?id a schema:Person; schema:name ?schema_name.
    FILTER langMatches(lang(?schema_name), "nl")

    OPTIONAL {
      ?id schema:deathDate ?schema_death_date
    }

    OPTIONAL {
      ?id schema:birthDate ?schema_birth_date
    }

    OPTIONAL {
      ?id schema:birthPlace/schema:name ?schema_birth_place
    }

    OPTIONAL {
      ?id schema:deathPlace/schema:name ?schema_death_place
    }
  }
}