PREFIX org: <http://www.w3.org/ns/org#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX haOrg: <https://data.hetarchief.be/ns/organization/>
PREFIX haPref: <https://data.hetarchief.be/id/organization-preferences/>

SELECT DISTINCT 
?id
?dcterms_description
?foaf_homepage
?ha_org_has_logo
?ha_org_request_form
?ha_org_sector
?org_classification
?org_identifier
?skos_pref_label
?created_at
?updated_at
WHERE {
  {
    SELECT ?id ?org_identifier (SAMPLE(?skos_pref_label_res) AS ?skos_pref_label)
    WHERE {
        ?id a org:Organization;
            org:identifier ?org_identifier;
            skos:prefLabel ?skos_pref_label_res.
      
        FILTER strStarts(?org_identifier, "OR-")
    }
    GROUP BY ?id ?org_identifier 
  }

  OPTIONAL { ?id dct:description ?dcterms_description }
  OPTIONAL { ?id dct:description ?dcterms_description }
  OPTIONAL { ?id foaf:homepage ?foaf_homepage }
  OPTIONAL { ?id haOrg:hasLogo ?ha_org_has_logo }
  OPTIONAL { ?id haOrg:requestForm ?ha_org_request_form } 
  OPTIONAL { ?id haOrg:sector ?ha_org_sector } 
  OPTIONAL { 
    ?id org:classification/skos:prefLabel ?org_classification .
    FILTER langMatches(lang(?org_classification), "nl") 
  }
}
