# position: 1
PREFIX premis: <http://www.loc.gov/premis/rdf/v3/>
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX haObj: <https://data.hetarchief.be/ns/object/> 
PREFIX haDes: <https://data.hetarchief.be/ns/description/> 
PREFIX haLicId: <https://data.hetarchief.be/id/license/>
PREFIX rel: <http://id.loc.gov/vocabulary/preservation/relationshipSubType/> 
PREFIX ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> 
prefix prov: <http://www.w3.org/ns/prov#>
# EBUCore - the Dublin Core for media
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> # XML Schema Definition
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT
?carrier_id
?ha_des_coloring_type
?created_at
?updated_at
WHERE {
  ?intellectual_entity_id rel:isr ?rep;  
      schema:license ?schema_license.
      
  # Only include the right licenses
  VALUES ?schema_license { 
    haLicId:VIAA-PUBLIEK-METADATA-LTD 
    haLicId:VIAA-PUBLIEK-METADATA-ALL
    haLicId:VIAA-PUBLIEK-CONTENT
    haLicId:BEZOEKERTOOL-METADATA-ALL
    haLicId:BEZOEKERTOOL-CONTENT 
    haLicId:VIAA-INTRA_CP-METADATA-ALL 
    haLicId:VIAA-INTRA_CP-CONTENT 
    haLicId:Publiek-Domein
    haLicId:COPYRIGHT-UNDETERMINED
  }
  ?rep premis:storedAt ?carrier_id.
  ?carrier_id a haObj:PhysicalCarrier ;
      haDes:coloringType/skos:prefLabel  ?ha_des_coloring_type
  FILTER langMatches(lang(?ha_des_coloring_type), "nl")
}