# position: 4
prefix schema: <https://schema.org/>

SELECT 
?intellectual_entity_id 
?type
?collection_id 
?created_at
?updated_at
WHERE {
  ?intellectual_entity_id schema:isPartOf ?collection_id.
  ?collection_id a ?type .

  VALUES ?type { schema:CreativeWorkSeries schema:Newspaper schema:CreativeWorkSeason schema:Episode  }
}