prefix skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT
?subject 
?predicate 
?object
?created_at
?updated_at
WHERE {
    ?subject a skos:Concept; ?predicate ?object_res.
    VALUES ?predicate { skos:prefLabel }
    FILTER langMatches(lang(?object_res), "nl")
    # TEMP FIX: filter out literals with newlines until CSV ouput is fixed
    #FILTER (!(regex(?object, "(\r\n|\r|\n)", "i")))
    BIND (IF(regex(?object_res, "(\r\n|\r|\n)", "i"),CONCAT("\"",?object_res,"\""),?object_res) AS ?object)
}
GROUP BY ?subject 
?predicate 
?object
?created_at
?updated_at