# position: 1
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX haOrg: <https://data.hetarchief.be/ns/organization/>

SELECT DISTINCT 
?organization_id
?ha_pref
?created_at
?updated_at
WHERE {
  ?organization_id a haOrg:ContentPartner;
      haOrg:hasPreference ?ha_pref_res .

   BIND (REPLACE(STR(?ha_pref_res), "^.*/([^/]*)$", "$1") as ?ha_pref)
}
