# position: 2
PREFIX schema: <https://schema.org/>
PREFIX haLicId: <https://data.hetarchief.be/id/license/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT 
?intellectual_entity_id 
?thing_id
?created_at
?updated_at
WHERE {
    ?intellectual_entity_id schema:mentions ?thing_id.
  
        # Do not include images
    FILTER NOT EXISTS {
      ?intellectual_entity_id dct:format "image".
    } 
    # Only include the right licenses
    FILTER EXISTS {
      ?intellectual_entity_id schema:license ?schema_license
      VALUES ?schema_license { 
        haLicId:VIAA-PUBLIEK-METADATA-LTD 
        haLicId:VIAA-PUBLIEK-METADATA-ALL
        haLicId:VIAA-PUBLIEK-CONTENT
        haLicId:BEZOEKERTOOL-METADATA-ALL
        haLicId:BEZOEKERTOOL-CONTENT 
        haLicId:VIAA-INTRA_CP-METADATA-ALL 
        haLicId:VIAA-INTRA_CP-CONTENT 
        haLicId:Publiek-Domein
        haLicId:COPYRIGHT-UNDETERMINED
    }
    }

    ?intellectual_entity_id prov:wasDerivedFrom/schema:dateModified ?modified .
    FILTER (!isLiteral(?since) || ?modified >= ?since )
}