# position: 2
PREFIX schema: <https://schema.org/>
PREFIX haLicId: <https://data.hetarchief.be/id/license/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> # SKOS Vocabulary
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT 
?intellectual_entity_id 
?schema_license
?created_at
?updated_at
WHERE {
    ?intellectual_entity_id schema:license ?schema_license_res.
    VALUES ?schema_license_res { 
        haLicId:VIAA-PUBLIEK-METADATA-LTD 
        haLicId:VIAA-PUBLIEK-METADATA-ALL
        haLicId:VIAA-PUBLIEK-CONTENT
        haLicId:BEZOEKERTOOL-METADATA-ALL
        haLicId:BEZOEKERTOOL-CONTENT 
        haLicId:VIAA-INTRA_CP-METADATA-ALL 
        haLicId:VIAA-INTRA_CP-CONTENT 
        haLicId:Publiek-Domein
        haLicId:COPYRIGHT-UNDETERMINED
    }

    FILTER NOT EXISTS {
      ?intellectual_entity_id dct:format "image".
    }

    BIND (REPLACE(STR(?schema_license_res), "^.*/([^/]*)$", "$1") as ?schema_license)


    ?intellectual_entity_id prov:wasDerivedFrom/schema:dateModified ?modified .
    FILTER (!isLiteral(?since) || ?modified >= ?since )
}